In [71]:
import pandas as pd

In [72]:
df_wine = pd.read_csv('winequality-white.csv', delimiter=';')


In [73]:
df_wine
X = df_wine.iloc[:, :-1]
y = df_wine.iloc[:, -1]

In [74]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.3, random_state=0)
X_train.shape

(3428, 11)

In [75]:
print(np.unique(y.values))
print(np.bincount(y.values))

[3 4 5 6 7 8 9]
[   0    0    0   20  163 1457 2198  880  175    5]


In [76]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [77]:
clf = LinearDiscriminantAnalysis()
clf.fit(X_train, y_train)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [78]:
clf.score(X_test, y_test)

0.5156462585034014

In [79]:
y = y.replace(3, 5)
y = y.replace(4, 5)
y = y.replace(9, 7)
y = y.replace(8, 7)

In [80]:
print(np.bincount(y))


X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.3, random_state=0)
X_train.shape


[   0    0    0    0    0 1640 2198 1060]


(3428, 11)

In [82]:
print('After uniting some classes: ')
clf = LinearDiscriminantAnalysis()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

After uniting some classes: 


0.55238095238095242